### PR TITLE
Add common and monitoring labels

### PR DESCRIPTION
**Pull request by omegas27**

### CODE REVIEW

**Comment by omegas27** [comment]
Tested on Gauss

**Comment by calvix** [comment]
did you tested update from the previous version as well?  playing with labels could result in errors with immutable fields

**Comment by omegas27** [comment]
Does that not apply only if I change the selector?

**Comment by omegas27** [comment]
Also, yes as I created a cluster first then I have overriden the app which "upgraded" it

**Comment by calvix** [comment]
> Does that not apply only if I change the selector?

not sure that's why asked if the update was tested and there were no errors :)

**Comment by omegas27** [comment]
Haha :D
It seems that it only applies to selectors yes https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#label-selector-updates

**Comment by calvix** [comment]
and you do changes to the label selector as well :package:

**Comment by omegas27** [comment]
I did not as I replaced `app: {{ .Values.name }}` with `{{- define "labels.selector" -}}
app: {{ .Values.name | quote }}
{{- end -}}`

**Pull request merged**
