### PR TITLE
Bump to 0.7.6

### PR DESCRIPTION
**Pull request by ubergesundheit**

### CODE REVIEW

**Comment by ubergesundheit** [comment]
Seems to work on AWS. The cluster on Azure is still creating

**Comment by calvix** [comment]
What is the progress here? it's blocking me for the 14.0.0 release

**Comment by ubergesundheit** [comment]
0.7.6 does not work on azure with this error:

```
level=error msg="Failed to extract targets for '....' with type 'NS'."
```

If its pressing, lets do a release 1.6.0 with 0.7.6 included. Otherwise I wanted to try to use `managed-record-types` flag for azure

**Comment by ubergesundheit** [comment]
@calvix seems the log line is not as bad as it sounds. Can you approve? Do I need to add this to the `requests.yaml` in releases?

**Review by calvix — APPROVED** [review]

**Comment by calvix** [comment]
i don't you need to add to the request for was as I will be updating it anyway

it's usually used when you need to force the version due to some important bugfix or compatibility

**Pull request merged**
